### ISSUE TITLE
arg-parsing implicit fakezod creation via -F/--fake regressed

### ISSUE THREAD

**Issue by barter-simsum** [urbit/vere#302]
#270 regressed past vere arg-parsing behavior.

The following now fails when it should succeed:
```
./urbit -F zod -B pill ./mypierwhichdoesntexityet
```

i.e. implicit pier creation when -F is specified.

implicit pier creation via -w is unaffected.

damage is minimal though because this would only affect developer workflows (e.g. mine) and most people probably give the redundant -c. Since it only applies to fakezods, hosting providers should be unaffected. Unsure what command that repl.it work was using. That could be affected as well. Or does that mine a comet? @matthew-levan for comment?

We should probably restore the old implicit pier creation. Alternatively, we can just leave it like this. The `-c` really is redundant though since -F should only be called for pier creation.

@ashelkovnykov

**Comment by ashelkovnykov** [comment]
I don't see this as a regression, so much as making `-c` function as intended: if you want to boot a new ship, you need to specify the name of the pier. When `-F` is specified, there is a default pier name corresponding to the name of the fake ship. When `-w` is specified, there is a default pier name corresponding to the name of the live ship. Otherwise, an explicit pier is required, since the only other option is to mine a comet and it's unknown what its name will be in advance.

@barter-simsum Aside from the GitHub workflow that broke until patched and your own personal scripts, have there been support requests related to this asking for the old behaviour to be restored? What standard or documentation are you using as a reference for "should succeed"?

**Comment by joemfb** [comment]
> When -F is specified, there is a default pier name corresponding to the name of the fake ship.

Isn't that precisely the behavior that regressed?

FWIW, the comet name is known before the pier directory is created. So that could also be the default, although it'd obviously be an awfully long name.

**Comment by ashelkovnykov** [comment]
> Isn't that precisely the behavior that regressed?

No, `./urbit -F zod` will still generate a pier at `./zod/`.

> FWIW, the comet name is known before the pier directory is created. So that could also be the default, although it'd obviously be an awfully long name.

It could be shortened as in `%groups`: `marzod_marzod`. However, this is a secondary concern.

It looks like the fundamental question is:

What behaviour is correct?
a) `-c` means "boot comet"; the `-c`, `-F`, and `-w` arguments are signals to use the first (and only) argument to `./urbit` as the path to which to save the pier, as opposed to the path from which to launch an existing pier
b) `-c` means "put new pier here"; if paired with `-F`, it's the pier for a fake ship; if paired with `-w`, it's the pier for a live ship; else, it's the pier of a comet

I thought (b) was the correct behaviour at the time that I submitted #270, but it looks like (a) might be what was originally intended.

**Comment by ashelkovnykov** [comment]
@barter-simsum Yeah, now that you've brought it up, I think that the (a) logic makes more sense, but based on how documentation/scripts are structured, (b) is the "local minima" for effort, so to speak.

I think the root of the current state of affairs is that `-c` was either born overloaded or became overloaded: boot comet *and* set pier.

**Comment by barter-simsum** [comment]
Yeah exactly. And I think if we break the cli as severely to make (a) the only option, we should just totally rewrite it with a more coherent cli strategy.
